# Generated by Django 2.2 on 2019-12-12 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saludo', '0002_lista_tareas_realizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=100)),
                ('fecha', models.DateField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=1, max_digits=3)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saludo.Categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Lista_tareas',
        ),
    ]
